import '../buttons/buttons.js'
import '../burger-menu/burger-menu.js'
import '../pay-button/pay-button.js'
import '../footer/footer.js'
import '../footer-mini/footer-mini.js'
import '../subscription-text-field/subscription-text-field.js'
import './header-w.scss'
