import './hotel-card.js'
import './cards.scss'
import '../../includes/modules/bill/bill.js'
import '../../includes/modules/pay-button/pay-button.js'
import '../../includes/modules/dropdown-accom/dropdown-accom.js'
import '../../includes/modules/buttons/buttons.js'
import '../../includes/modules/hotel-card/hotel-card.js'
import '../../includes/modules/toggle/toggle.js'
import '../../includes/modules/date-picker/date-picker.js'
import '../../includes/modules/filter-date-dropdown/filter-date-dropdown.js'
// import '../../daterangepicker-master/daterangepicker.css'
