import '../../layout/fonts.scss'
import '../../layout/default-input.scss'
import '../../layout/landing.scss'
import '../../layout/main.scss'
import '../../layout/mixins.scss'
import '../../layout/nullstyle.scss'
import '../../layout/vars.scss'
import './index.scss'
import '../../includes/modules/header-w/header-w.js'
import '../../includes/modules/footer/footer.js'
import '../../includes/modules/footer-mini/footer-mini.js'
import '../../includes/modules/burger-menu/burger-menu.js'
import '../base/base.scss'
console.log(process.env.NODE_ENV)
