import '../../layout/fonts.scss'
import '../../layout/default-input.scss'
import '../../layout/landing.scss'
import '../../layout/main.scss'
import '../../layout/mixins.scss'
import '../../layout/nullstyle.scss'
import '../../layout/vars.scss'
import './index.scss'
import '../../includes/modules/header-w/header-w.js'
import '../../includes/modules/footer/footer.js'
import '../../includes/modules/footer-mini/footer-mini.js'

import '../../includes/modules/sign-in/sign-in.js'
import '../../includes/modules/registration/registration.js'
import '../../includes/modules/rooms-for-you/rooms-for-you.js'
import '../../includes/modules/burger-menu/burger-menu.js'
import '../base/base.scss'
