import './hotel-card.js'
import '../../includes/modules/bullet-list/bullet-list.js'
import '../../includes/modules/graph/graph.js'
import '../../includes/modules/comment/comment.js'
import '../../includes/modules/bill/bill.js'
import '../../includes/modules/features/features.js'
import '../../includes/modules/date-picker/date-picker.js'
import '../../includes/modules/hotel-card/hotel-card.js'
import '../../includes/modules/dropdown-accom/dropdown-accom.js'

import './roomDetails.scss'
