// import '../../includes/modules/toggle/toggle.js'
// import '../../includes/modules/radio-buttons/radio-buttons.js'
// import '../../includes/modules/toggle/toggle.js'
import '../../includes/modules/registration/registration.js'
import './registration.scss'
